name: Laravel CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Compatible avec Laravel 11
          extensions: mbstring, dom, fileinfo, sqlite, curl, zip
          coverage: xdebug # Optionnel pour la couverture de code

      # Étape 3 : Installer les dépendances Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Étape 4 : Configurer le fichier .env
      - name: Set up environment file
        run: |
          cp .env.example .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env

      # Étape 5 : Générer une clé d'application (si non fournie)
      - name: Generate application key
        run: php artisan key:generate || true

      # Étape 6 : Exécuter les tests Pest
      - name: Run Pest tests
        run: php artisan test
