name: Laravel CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Utilise la version de PHP compatible avec Laravel 11
          extensions: mbstring, dom, fileinfo, sqlite, curl, zip # Extensions nécessaires
          coverage: xdebug # Optionnel pour les rapports de couverture de code

      # Étape 3 : Installer les dépendances Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

#      # Étape 4 : Générer une clé d'application Laravel
#      - name: Generate Laravel application key
#        run: php artisan key:generate
#
#      # Étape 5 : Exécuter les migrations (si nécessaire)
#      - name: Run migrations
#        run: php artisan migrate:fresh --env=testing --force

      # Étape 6 : Exécuter les tests Pest
      - name: Run Pest tests
        run: php artisan test
